Написал функцию CheckPlayerDeath
csit-sgu/mit-game-111 pull request #26
Opened 2023-05-17 16:38 UTC by Maxims512

2023-05-18 09:53 UTC, mchernigin commented
Нужно запросить проверку, указав нас в Reviewers и себя в Assignees, и связать с соответствующей задачей во разделе Development.

2023-05-23 19:47 UTC, nrydanov requested changes

2023-05-23 19:47 UTC, nrydanov commented on user.cpp
> +            if (CheckCollision(player, object).exists) { // Проверка на столконовение
Не стоит оставлять комментарии в той же строчке, где открывается область видимости

2023-05-28 14:42 UTC, vasthecat approved these changes
ладно норм

2023-05-29 18:08 UTC, mchernigin approved these changes
Было бы неплохо вместо вложенных конструкций `if` использовать логическое и `&&`...

2023-05-30 20:10 UTC, Maxims512 commented on user.cpp
> +            if (CheckCollision(player, object).exists) { // Проверка на столконовение
Исправил

2023-05-30 20:13 UTC, nrydanov approved these changes

2023-05-30 20:16 UTC, merged