Реализовал функцию отрисовки основного экрана
csit-sgu/mit-game-111 pull request #27
Opened 2023-05-18 16:29 UTC by 5TEMIR

2023-05-23 19:43 UTC, nrydanov requested changes

2023-05-23 19:43 UTC, nrydanov commented on user.cpp
> +	// очищаем экран и устанавливаем фоновый цвет
Верни, пожалуйста, таб на место... убежал)

2023-05-23 19:43 UTC, nrydanov commented on user.cpp
> +    BeginDrawing();
BeginDrawing запускается в основном цикле игры (внутри `main.cpp`). Здесь эти инструкции всё ломают, потому что у тебя каждый кадр заново начинается процесс отрисовки.

2023-05-23 19:43 UTC, nrydanov commented on user.cpp
> +    ClearBackground(BLACK);
Этого здесь тоже быть не должно.

2023-05-28 14:37 UTC, vasthecat approved these changes
Похоже на правду

2023-05-29 18:07 UTC, mchernigin commented
А зачем ты удалил текст под заголовком?

2023-05-29 18:15 UTC, 5TEMIR commented
Решил, будет лишним

2023-05-30 20:13 UTC, nrydanov approved these changes

2023-05-30 20:18 UTC, merged