Реализовал функцию ApplyOnDeath
csit-sgu/mit-game-111 pull request #28
Opened 2023-05-18 22:16 UTC by b9cv9

2023-05-23 19:33 UTC, nrydanov requested changes

2023-05-23 19:33 UTC, nrydanov commented on user.cpp
> +	string soundPath;
Исправь, пожалуйста, табуляцию

2023-05-23 19:33 UTC, nrydanov commented on user.cpp
> +    else if (obj.enemy.enabled) soundPath = "Assets/Sounds/enemy_death.mp3";
Ифы лесенкой — не очень красиво. Где-то табы не совпадают по величине, в общем, лучше не жалеть {, а то читать трудно

2023-05-23 19:37 UTC, nrydanov requested changes

2023-05-23 19:37 UTC, nrydanov commented on user.cpp
> +using namespace std;
Если в олимпиадах или маленьких домашках `using namespace` норм идея, то в реальном коде так делать очень нерекомендуется.

Если коротко — это создает много коллизий имен и может приводить к неразберихе.

Если длинно — подойди и расскажу по-подробнее, в чем тут беда.

2023-05-29 08:06 UTC, vasthecat approved these changes

2023-05-29 08:06 UTC, vasthecat commented on user.cpp
> +	//переменная, принимающая в себя путь к звуку
Такие бесполезные комментарии не несут смысловую нагрузку. Все комментарии в функции лучше убрать, но за ошибку считать это не буду.

2023-05-29 18:05 UTC, mchernigin requested changes
Избыточное количество комментариев и большие проблемы с форматированием кода.

Звуки хорошие. Позитивные.

2023-05-29 18:05 UTC, mchernigin commented on user.cpp
> +    	if (obj.player.enabled) {
Уехал на таб вправо

2023-05-29 18:05 UTC, mchernigin commented on user.cpp
> +    	else if (obj.enemy.enabled) {
И здесь

2023-05-30 11:24 UTC, b9cv9 commented on user.cpp
> +    	else if (obj.enemy.enabled) {
исправил

2023-05-30 11:26 UTC, nrydanov requested changes

2023-05-30 11:26 UTC, nrydanov commented on user.cpp
> +	std::string soundPath;
Опять поехал таб, тут один лишний

2023-05-30 11:26 UTC, nrydanov commented on user.cpp
> +		//если является игроком, то присваиваем soundPath нужный путь
И здесь 1 лишний уровень

2023-05-30 11:26 UTC, nrydanov commented on user.cpp
> +		//если является врагом, то присваиваем soundPath нужный путь
И здесь

2023-05-30 11:48 UTC, b9cv9 commented on user.cpp
> +		//если является врагом, то присваиваем soundPath нужный путь
ёмаё да как починить то) у меня просто корректно всё отображается, щас попробую исправить

2023-05-30 12:32 UTC, nrydanov approved these changes
Чё-то длинный какой-то таб, но ладно...

2023-05-30 19:54 UTC, b9cv9 commented on user.cpp
> +    	else if (obj.enemy.enabled) {
> И здесь

всё исправил не мог бы пожалуйста чекнуть

2023-05-30 19:57 UTC, mchernigin approved these changes
🆗

2023-05-30 20:12 UTC, merged