Реализовал функцию ConstructMenuScene
csit-sgu/mit-game-111 pull request #29
Opened 2023-05-20 17:46 UTC by Antareees

2023-05-23 19:30 UTC, nrydanov requested changes
Нужно убрать изменения со всех функций, к которым PR не имеет отношения и пофиксить функцию

2023-05-23 19:30 UTC, nrydanov commented on user.cpp
> -	const Vector2 GRAVITY({ 0, -90 });
Аналогично тому, что выше

2023-05-23 19:30 UTC, nrydanov commented on user.cpp
> +	string path_bg = "Assets/menu_background.png";
А как оно будет собираться, если string без пространства имен std, а пространство нигде не подключается?

2023-05-23 19:30 UTC, nrydanov commented on user.cpp
> +	bg.render =  Render(path_bg, size_bg);
Render не вызовется

2023-05-29 08:47 UTC, vasthecat requested changes
Твоя функция запускается одной из самых первых и фактически не зависит ни от каких других функций, так как выполняется для совсем другой сцены. Почему нельзя было запустить и увидеть, что ничего не работает, мне не понятно.

2023-05-29 08:47 UTC, vasthecat commented on user.cpp
> +	std::string path_bg = "Assets/menu_background.png";
Эта картинка не подгружается из-за ошибки
```
INFO: FILEIO: [Assets/menu_background.png] File loaded successfully
WARNING: IMAGE: Failed to load image data
WARNING: IMAGE: Data is not valid to load texture
```

2023-05-29 08:47 UTC, vasthecat commented on user.cpp
> +	float size_button = (ctx.screen_size.x * ctx.screen_size.y * 0.05) / (800 * 450); // размер кнопки составляет 5% от экрана
Не знаю что за рассчёты, но кнопка тоже не отрисовывается.

2023-05-29 08:47 UTC, vasthecat commented on user.cpp
> +	float size_button = (ctx.screen_size.x * ctx.screen_size.y * 0.05) / (800 * 450); // размер кнопки составляет 5% от экрана
Также данная строка слишком длинная -- нужно меньше 80 символов.

2023-05-29 08:47 UTC, vasthecat commented on user.cpp
> +	std::string path_button = "Assets/background.png";
Файл `Assets/background.png` отвечает за фоновую картинку в сцене с игрой. Эта текстура меняется в другом задании, поэтому верни картинку, которая была до этого. Свою можешь назвать, например, `button.png`.

2023-05-29 17:58 UTC, mchernigin approved these changes
Очень скудно, но оно хотя бы работает

2023-05-30 18:12 UTC, vasthecat approved these changes

2023-05-30 18:13 UTC, nrydanov approved these changes

2023-05-31 05:04 UTC, merged