(EnemyAI) ИИ противников #10
csit-sgu/mit-game-111 pull request #30
Opened 2023-05-21 15:25 UTC by VDolesov

2023-05-23 19:20 UTC, nrydanov requested changes
В общем... пока рано.

2023-05-23 19:20 UTC, nrydanov commented on user.cpp
> +		// Изменим позицию врага в зависимости от положения игрока
Строчка поехала... верни, пожалуйста, её на место)

2023-05-23 19:20 UTC, nrydanov commented on user.cpp
> +
А тут-то зачем пустая строчка

2023-05-23 19:20 UTC, nrydanov commented on user.cpp
> +
И тут...

2023-05-23 19:20 UTC, nrydanov commented on Assets/enemy_Valentin.png
Текстурка должна называться как enemy1.png, либо пусть называется так, но тогда нужно найти исправить код, который подгружает текстурку :)

2023-05-23 19:20 UTC, nrydanov commented on Assets/enemy_by_Valentin.png
а две-то зачем...

2023-05-28 14:51 UTC, vasthecat commented on user.cpp
> +	// Получим скорость движения врага
Вот такие бесполезные комментарии лучше вообще не оставлять. Смысловой нагрузки они не несут, но читать код немного сложнее просто потому что строчек больше и вокруг них какой-то мусор.

2023-05-28 14:51 UTC, vasthecat approved these changes
Сойдёт

2023-05-28 17:29 UTC, nrydanov requested changes
Вторую картинку с врагом нужно убрать... У тебя и `enemy_Valentin` и `enemy_by_Valentin` в репозитории будут.

2023-05-28 17:55 UTC, nrydanov requested changes

2023-05-28 17:55 UTC, nrydanov commented on user.cpp
> +	auto enemy_pos = enemy.position;
Все ещё много малоинформативных комментов... лучше убрать все

2023-05-28 18:04 UTC, nrydanov approved these changes

2023-05-28 18:04 UTC, nrydanov commented on user.cpp
> +	// Вычислим разницу между игроком и врагом
Я хотел, чтобы ты совсем все удалил, но ладно...

2023-05-28 18:05 UTC, nrydanov approved these changes

2023-05-28 18:15 UTC, merged