KillEnemies
csit-sgu/mit-game-111 pull request #31
Opened 2023-05-23 19:14 UTC by msklnkk

close: #14

2023-05-23 19:54 UTC, nrydanov requested changes
Не скомпилируется

2023-05-23 19:54 UTC, nrydanov commented on user.cpp
> +		if (obj.enemy.enable) {
У Enemy нет объекта типа enable

2023-05-23 19:54 UTC, nrydanov commented on user.cpp
> +					if (CheckCollision(obj, bullet)) {
Объект типа Collision не может конвертироваться в bool

2023-05-29 17:53 UTC, mchernigin approved these changes
Слишком много комментариев, которые не добавляют смысла, но ладно

2023-05-29 20:50 UTC, nrydanov approved these changes

2023-05-30 02:46 UTC, merged