20 applyonspawn sound for shot
csit-sgu/mit-game-111 pull request #35
Opened 2023-05-27 18:04 UTC by qd310

2023-05-28 14:46 UTC, vasthecat requested changes
И проставь Reviewers и Assignee

2023-05-28 14:46 UTC, vasthecat commented on user.cpp
> +		Sound soundShot = LoadSound(ctx, "Assets/Sounds/shot.mp3");
LoadSound не принимает ctx как параметр. У 151 мы пропустили эту ошибку, но она и тут каким-то интересным образом получилась...

2023-05-29 08:50 UTC, vasthecat approved these changes

2023-05-29 08:51 UTC, mchernigin approved these changes

2023-05-29 13:39 UTC, merged